## Basic Configuration
baseurl = "https://www.alottolearn.net"
languageCode = "en"

title = "A lot to learn.NET"
theme = "hyde"

## Hugo Built-in Features
disqusShortname = "alottolearn-net"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Rick Neeft"
    title = "Title"
    # description = "..."
    authorimage = "/img/profile.png"
    dateformat = "2 January 2006"

    # sidebar, copyright & license
    copyright = "Rick Neeft"
    since = 2020
    license = ""
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "rneeft"
    linkedin = "rneeft"
    twitter = "rneeft"
    stackoverflow = "rick-neeft"
    email = "rick@chroomsoft"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
